### ISSUE TITLE
a proposal to simplify the logic of consuming memory

### ISSUE THREAD

**Issue by YangKeao** [chaos-mesh/memStress#1]
Calculate the consuming memory according to the now and start time could get a much simpler logic:

```
expect = length * (now - start) / (end - start)
```

Then we need to consume the `expect - allocated` bytes. The sleep interval could be a constant value. For example:

```go
startTime := time.Now()
endTime := startTime.Add(time.Duration(timeLine))

allocated := 0
pageSize := int(syscall.Getpagesize())
interval := time.Millisecond * 10

for {
    now := time.Now()
    if now.After(endTime) {
	    now = endTime
    }
    expected := length * int(now.Sub(startTime).Milliseconds()) / int(endTime.Sub(startTime).Milliseconds()) / pageSize
    
    for i := allocated; i < expected; i++ {
	    data[i*pageSize] = 0
    }
    
    allocated = expected
    if now.Equal(endTime) {
	    break
    } else {
	    time.Sleep(interval)
    }
}
```

Then we can be sure that the upper bound of allocation time will be not bigger than the interval (unless the CPU is too slow or timeLine is too short).

**Comment by FingerLeader** [comment]
After some test, I think your implementation is better than mine. Your code is more clean and simple, are you willing to pull request or I apply the changes directly?

**Comment by YangKeao** [comment]
> After some test, I think your implementation is better than mine. Your code is more clean and simple, are you willing to pull request or I apply the changes directly?

You could do it yourself :+1: .
